-- Run this SQL in Supabase Dashboard → SQL Editor
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamptz default now()
);

-- Keep the table private. The Next.js server inserts messages using the service role key.
alter table public.messages enable row level security;

-- Optional: prevent direct browser access to the table.
revoke all on table public.messages from anon, authenticated;
